export const User=[
    {
        name:"Arun",
        math:79,
        hindi:80,
        english:65,
        science:90,
        social_studies:82,
    },
    {
        name:"Bhanu",
        math:79,
        hindi:85,
        english:65,
        science:60,
        social_studies:72,
    },
    {
        name:"Suraj",
        math:79,
        hindi:80,
        english:65,
        science:90,
        social_studies:82,
    },
    {
        name:"Abhishek",
        math:69,
        hindi:80,
        english:65,
        science:80,
        social_studies:87,
    },
  
]